### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Waldo-Schaeffer**

### CODE REVIEW

**Comment by ElektroStudios** [comment]
Hi @Waldo-Schaeffer 

Can you explain the purpose of the edits you did on the file?, excuse me but I don't get it at all. The Paypal hyperlink is working properly.

**Comment by Waldo-Schaeffer** [comment]
> 嗨@ Waldo-Schaeffer
> 
> 您能解释一下对文件进行编辑的目的吗？对不起，但我完全不了解。贝宝超链接工作正常。

i copy this repositories' readme.md and edit other repositories readme.md. but i copy with wrong repositories. i am a newbee

**Comment by Waldo-Schaeffer** [comment]
> 嗨@ Waldo-Schaeffer
> 
> 您能解释一下对文件进行编辑的目的吗？对不起，但我完全不了解。贝宝超链接工作正常。

this is my first use github desktop in my computer

**Comment by Waldo-Schaeffer** [comment]
> 嗨@ Waldo-Schaeffer
> 
> 您能解释一下对文件进行编辑的目的吗？对不起，但我完全不了解。贝宝超链接工作正常。

i just want create a new repositories. but i didn't know how to Initialize repository.

**Comment by Waldo-Schaeffer** [comment]
> Hi @Waldo-Schaeffer
> 
> Can you explain the purpose of the edits you did on the file?, excuse me but I don't get it at all. The Paypal hyperlink is working properly.

now i private my patch. i am so sorry to make you confused.

**Comment by ElektroStudios** [comment]
Don't worry about it. You're welcome. :)

Since I think to understand this pull request was a mistake from your side, I'll close it. 

If what you really want to do is to create a full copy/clone of this repository, what you need to perform is a Fork. I'll link the docs for you:

https://help.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by Waldo-Schaeffer** [comment]
> 嗨@ Waldo-Schaeffer
> 
> 您能解释一下对文件进行编辑的目的吗？对不起，但我完全不了解。贝宝超链接工作正常。



> Don't worry about it. You're welcome. :)
> 
> Since I think to understand this pull request was a mistake from your side, I'll close it.
> 
> If what you really want to do is to create a full copy/clone of this repository, what you need to perform is a Fork. I'll link the docs for you:
> 
> https://help.github.com/en/github/getting-started-with-github/fork-a-repo


> Don't worry about it. You're welcome. :)
> 
> Since I think to understand this pull request was a mistake from your side, I'll close it.
> 
> If what you really want to do is to create a full copy/clone of this repository, what you need to perform is a Fork. I'll link the docs for you:
> 
> https://help.github.com/en/github/getting-started-with-github/fork-a-repo

thank u very much

**Comment by Waldo-Schaeffer** [comment]
> Don't worry about it. You're welcome. :)
> 
> Since I think to understand this pull request was a mistake from your side, I'll close it.
> 
> If what you really want to do is to create a full copy/clone of this repository, what you need to perform is a Fork. I'll link the docs for you:
> 
> https://help.github.com/en/github/getting-started-with-github/fork-a-repo

thank u very much

**Pull request closed without merging**
